version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    env_file:
      - ./.env.db
  web:
    build: ./homestream
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./homestream:/home/homestream/web
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev

volumes:
  postgres_data: