# Generated by Django 2.2.9 on 2020-04-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbs/')),
                ('file_obj', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
